FROM golang:1.20 AS dev

WORKDIR /go/src/github.com/cryptobranchoidea/fisap

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@v1.29.0

COPY docker/dev/api/.air.toml /air/.air.toml

CMD ["air", "-c", "/air/.air.toml"]